import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import { Header, Main, Footer, Root } from "../components/Layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MemBox</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Root>
        <Header>
          <div>Logo</div>
          <div>Search</div>
          <div>Login</div>
        </Header>
        <Main>
          <div>Left</div>
          <div>Right</div>
        </Main>
        <Footer />
      </Root>
    </div>
  );
};

export default Home;
