import { Box } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import { Header, Main, Footer, Root } from "../components/Layout";
import { Right } from "../components/Right";
import logo from "../../public/logo.png";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MemBox</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Root>
        <Header>
          <div>
            {/* <Image src={logo} width="20px" height="20px"></Image> */}
            Logo
          </div>
          <div>Search</div>
          <div>Login</div>
        </Header>
        <Main>
          <Box
            sx={{
              // border: "1px solid orange",
              minWidth: "250px",
              backgroundColor: "secondary.main",
            }}
          >
            Left
          </Box>
          {/* <div
            style={{
              border: "1px solid purple",
              flex: 1,
              // width: "250px",
            }}
          >
            Right
          </div> */}
          <Right />
        </Main>
        <Footer />
      </Root>
    </div>
  );
};

export default Home;
